/* =========================================================
   PASSWORD — football name-picker (separate from the
   stories/investigation games above; no player/GM roles)
========================================================= */

const FOOTBALL_PLAYERS=[
"Diego Maradona",
"Lionel Messi",
"Cristiano Ronaldo",
"Johan Cruyff",
"Franz Beckenbauer",
"Alfredo Di Stéfano",
"Ferenc Puskás",
"Michel Platini",
"Zinedine Zidane",
"Ronaldinho",
"Garrincha",
"Eusébio",
"George Best",
"Bobby Charlton",
"Paolo Maldini",
"Xavi",
"Andrés Iniesta",
"Luka Modrić",
"Romário",
"Marco van Basten",
"Ruud Gullit",
"Frank Rijkaard",
"Lev Yashin",
"Gerd Müller",
"Bobby Moore",
"Stanley Matthews",
"Didi",
"Vavá",
"Cafu",
"Roberto Carlos",
"Sergio Ramos",
"Carles Puyol",
"Franco Baresi",
"Gaetano Scirea",
"Lothar Matthäus",
"Andrea Pirlo",
"Alessandro Del Piero",
"Roberto Baggio",
"Francesco Totti",
"Paolo Rossi",
"Fabio Cannavaro",
"Gianluigi Buffon",
"Iker Casillas",
"Manuel Neuer",
"Oliver Kahn",
"Peter Schmeichel",
"Dino Zoff",
"Gordon Banks",
"Thierry Henry",
"Kaká",
"Luis Figo",
"Neymar",
"Kylian Mbappé",
"Erling Haaland",
"Kevin De Bruyne",
"Mohamed Salah",
"Karim Benzema",
"Robert Lewandowski",
"Sergio Agüero",
"Luis Suárez",
"Edinson Cavani",
"Zlatan Ibrahimović",
"David Beckham",
"Wayne Rooney",
"Steven Gerrard",
"Frank Lampard",
"Paul Scholes",
"Ryan Giggs",
"Roy Keane",
"Patrick Vieira",
"Claude Makélélé",
"Didier Drogba",
"Samuel Eto'o",
"Yaya Touré",
"Riyad Mahrez",
"Sadio Mané",
"Vincent Kompany",
"Virgil van Dijk",
"Arjen Robben",
"Wesley Sneijder",
"Clarence Seedorf",
"Dennis Bergkamp",
"Ruud van Nistelrooy",
"Robin van Persie",
"Edgar Davids",
"Patrick Kluivert",
"Ruud van Nistelrooij",
"Jari Litmanen",
"Michael Laudrup",
"Brian Laudrup",
"Peter Beardsley",
"Alan Shearer",
"Eric Cantona",
"George Weah",
"Jay-Jay Okocha",
"Nwankwo Kanu",
"Abedi Pele",
"Hristo Stoichkov",
"Dimitar Berbatov",
"Davor Šuker",
"Robert Prosinečki",
"Zvonimir Boban",
"Dejan Savićević",
"Predrag Mijatović",
"David Villa",
"Fernando Torres",
"Raúl",
"Xabi Alonso",
"Sergio Busquets",
"Gerard Piqué",
"Dani Alves",
"Jordi Alba",
"David Silva",
"Cesc Fàbregas",
"Juan Mata",
"Isco",
"David de Gea",
"Thibaut Courtois",
"Eden Hazard",
"Romelu Lukaku",
"Kevin-Prince Boateng",
"Mesut Özil",
"Toni Kroos",
"Thomas Müller",
"Bastian Schweinsteiger",
"Miroslav Klose",
"Philipp Lahm",
"Mats Hummels",
"Jerome Boateng",
"Per Mertesacker",
"Sami Khedira",
"Ilkay Gündogan",
"Joshua Kimmich",
"Kai Havertz",
"Florian Wirtz",
"Jamal Musiala",
"Thomas Hässler",
"Michael Ballack",
"Jürgen Klinsmann",
"Rudi Völler",
"Karl-Heinz Rummenigge",
"Matthias Sammer",
"Oliver Bierhoff",
"Jürgen Kohler",
"Andreas Brehme",
"Bernd Schuster",
"Lukas Podolski",
"Mario Götze",
"Marco Reus",
"Marius Trésor",
"Just Fontaine",
"Raymond Kopa",
"Jean Tigana",
"Jean-Pierre Papin",
"Laurent Blanc",
"Marcel Desailly",
"Lilian Thuram",
"Franck Ribéry",
"Antoine Griezmann",
"Paul Pogba",
"N'Golo Kanté",
"Olivier Giroud",
"Raphaël Varane",
"William Saliba",
"Theo Hernández",
"Mike Maignan",
"Hugo Lloris",
"Bixente Lizarazu",
"Didier Deschamps",
"Robert Pirès",
"David Trezeguet",
"Nicolas Anelka",
"Zbigniew Boniek",
"Grzegorz Lato",
"Kazimierz Deyna",
"Włodzimierz Lubański",
"Robert Gadocha",
"Jerzy Gorgoń",
"Bohdan Masztaler",
"Andriy Shevchenko",
"Oleg Blokhin",
"Igor Belanov",
"Rinat Dasayev",
"Oleksandr Zavarov",
"Serhiy Rebrov",
"Oleh Luzhnyi",
"Yevhen Konoplyanka",
"Andriy Yarmolenko",
"Anatoliy Tymoshchuk",
"Henrikh Mkhitaryan",
"Roger Milla",
"Rabah Madjer",
"Lakhdar Belloumi",
"Mustapha Hadji",
"Mehdi Benatia",
"Hakim Ziyech",
"Achraf Hakimi",
"Youssef En-Nesyri",
"Sofyan Amrabat",
"Nordin Amrabat",
"Nayef Aguerd",
"Medhi Benatia",
"Hassan Akesbi",
"Ahmed Faras",
"Salaheddine Bassir",
"El Hadji Diouf",
"Papiss Cissé",
"Kalidou Koulibaly",
"Cheikh Tioté",
"Michael Essien",
"Sulley Muntari",
"Kwadwo Asamoah",
"Asamoah Gyan",
"Stephen Appiah",
"Tony Yeboah",
"Samuel Kuffour",
"John Paintsil",
"Boubacar Barry",
"Didier Zokora",
"Emmanuel Adebayor",
"Rashidi Yekini",
"Sunday Oliseh",
"Finidi George",
"Taribo West",
"Joseph Yobo",
"Victor Ikpeba",
"Daniel Amokachi",
"Austin Jay-Jay Okocha",
"Vincent Enyeama",
"Victor Moses",
"Wilfred Ndidi",
"Victor Osimhen",
"Alex Iwobi",
"Ahmed Musa",
"Samuel Chukwueze",
"John Obi Mikel",
"Obafemi Martins",
"Yakubu",
"Peter Odemwingie",
"Celestine Babayaro",
"Stephen Keshi",
"Sunday Mba",
"Emmanuel Emenike",
"Edouard Mendy",
"Idrissa Gueye",
"Nampalys Mendy",
"Patrice Evra",
"Blaise Matuidi",
"Islam Slimani",
"Yacine Brahimi",
"Sofiane Feghouli",
"Saïd Benrahma",
"Ismaël Bennacer",
"Rachid Ghezzal",
"Youcef Belaïli",
"Baghdad Bounedjah",
"Aïssa Mandi",
"Djamel Belmadi",
"Mustapha Dahleb",
"Ali Benarbia",
"Rafik Saïfi",
"Karim Ziani",
"Saphir Taïder",
"Adel Taarabt",
"Marouane Chamakh",
"Nabil Dirar",
"Amine Harit",
"Abdelaziz Barrada",
"Younès Belhanda",
"Mounir El Haddadi",
"Tarik Sektioui",
"Noureddine Naybet",
"Walid Regragui",
"Badou Zaki",
"Tahar El Khalej",
"Houssine Kharja",
"Abderrahim Ouakili",
"Youssef Chippo",
"Noureddine Boukhari",
"Anas Zniti",
"Abdeljalil Hadda",
"Hassan Nader",
"Abdelkader Ghezzal",
"Karim El Ahmadi",
"Mbark Boussoufa",
"Mounir Obbadi",
"Marouane Fellaini",
"Dries Mertens",
"Jan Vertonghen",
"Toby Alderweireld",
"Thomas Vermaelen",
"Axel Witsel",
"Radja Nainggolan",
"Yannick Carrasco",
"Leandro Trossard",
"Youri Tielemans",
"Amadou Onana",
"Charles De Ketelaere",
"Jeremy Doku",
"Michy Batshuayi",
"Divock Origi",
"Christian Benteke",
"Nacer Chadli",
"Mousa Dembélé",
"Kevin Mirallas",
"Emile Mpenza",
"Mbo Mpenza",
"Enzo Scifo",
"Michel Preud'homme",
"Jean-Marie Pfaff",
"Franky Van der Elst",
"Marc Wilmots",
"Georges Grün",
"Luc Nilis",
"Johan Boskamp",
"Jan Ceulemans",
"Danny Boffin",
"Marc Degryse",
"Philippe Albert",
"Thomas Meunier",
"Simon Mignolet",
"Koen Casteels",
"Timmy Simons",
"Nico Claesen",
"Wilfried Van Moer",
"Paul Van Himst",
"Ewald Lienen",
"Sepp Maier",
"Harald Schumacher",
"Hans-Jürgen Dörner",
"Uwe Seeler",
"Fritz Walter",
"Helmut Rahn",
"Wolfgang Overath",
"Paul Breitner",
"Günter Netzer",
"Jupp Heynckes",
"Klaus Fischer",
"Horst Hrubesch",
"Karl-Heinz Förster",
"Klaus Augenthaler",
"Hans-Georg Schwarzenbeck",
"Rainer Bonhof",
"Manfred Kaltz",
"Berti Vogts",
"Jürgen Grabowski",
"Pierre Littbarski",
"Karl-Heinz Riedle",
"Thomas Doll",
"Andreas Möller",
"Thomas Strunz",
"Stefan Effenberg",
"Mehmet Scholl",
"Jens Lehmann",
"Kevin Kurányi",
"Claudio Pizarro",
"Paolo Guerrero",
"Jefferson Farfán",
"Hernán Crespo",
"Gabriel Batistuta",
"Claudio Caniggia",
"Javier Zanetti",
"Juan Sebastián Verón",
"Ariel Ortega",
"Pablo Aimar",
"Juan Román Riquelme",
"Javier Saviola",
"Carlos Tevez",
"Ángel Di María",
"Gonzalo Higuaín",
"Lautaro Martínez",
"Julián Álvarez",
"Rodrigo De Paul",
"Enzo Fernández",
"Alexis Mac Allister",
"Leandro Paredes",
"Nicolás Otamendi",
"Lisandro Martínez",
"Emiliano Martínez",
"Javier Mascherano",
"Esteban Cambiasso",
"Éver Banega",
"Pablo Zabaleta",
"Gabriel Heinze",
"Walter Samuel",
"Martín Demichelis",
"Gabriel Milito",
"Diego Milito",
"Hugo Ibarra",
"Roberto Ayala",
"Oscar Ruggeri",
"José Chamot",
"Fernando Redondo",
"Diego Simeone",
"Claudio López",
"Marcelo Gallardo",
"Marcelo Salas",
"Iván Zamorano",
"Alexis Sánchez",
"Arturo Vidal",
"Claudio Bravo",
"Gary Medel",
"Eduardo Vargas",
"Charles Aránguiz",
"David Pizarro",
"Jorge Valdivia",
"Mauricio Isla",
"Jean Beausejour",
"Marcelo Díaz",
"Matías Fernández",
"Humberto Suazo",
"Iván Hurtado",
"Agustín Delgado",
"Édison Méndez",
"Antonio Valencia",
"Enner Valencia",
"Moisés Caicedo",
"Kendry Páez",
"Alex Aguinaga",
"Álex Aguinaga",
"Iván Kaviedes",
"Jefferson Montero",
"Christian Noboa",
"José Luis Chilavert",
"Roque Santa Cruz",
"Salvador Cabañas",
"José Cardozo",
"Carlos Gamarra",
"Romerito",
"Francisco Arce",
"Julio Enciso",
"Miguel Almirón",
"Darío Verón",
"Nelson Valdez",
"Óscar Cardozo",
"Raúl Vicente Amarilla",
"Carlos Valderrama",
"René Higuita",
"Faustino Asprilla",
"Radamel Falcao",
"James Rodríguez",
"Juan Cuadrado",
"David Ospina",
"Mario Yepes",
"Iván Córdoba",
"Freddy Rincón",
"Adolfo Valencia",
"Arnoldo Iguarán",
"Carlos Bacca",
"Jackson Martínez",
"Duván Zapata",
"Luis Díaz",
"Jhon Durán",
"Juan Fernando Quintero",
"Teófilo Gutiérrez",
"Víctor Aristizábal",
"Willington Ortiz",
"Efraín Sánchez",
"Pedro Zape",
"Marcos Coll",
"Jorge Bermúdez",
"Anthony de Ávila",
"Elkin Soto",
"Fredy Guarín",
"Abel Aguilar",
"Carlos Sánchez",
"Yerry Mina",
"Cristian Zapata",
"Jeison Murillo",
"Davinson Sánchez",
"William Tesillo",
"Juan Pablo Ángel",
"Hugo Rodallega",
"Zico",
"Sócrates",
"Rivelino",
"Jairzinho",
"Tostão",
"Careca",
"Bebeto",
"Dunga",
"Aldair",
"Lucio",
"Thiago Silva",
"Marquinhos",
"Daniel Alves",
"Marcelo",
"Robinho",
"Adriano",
"Rivaldo",
"Ramires",
"Juninho Pernambucano",
"Juninho Paulista",
"Gilberto Silva",
"Emerson",
"Mauro Silva",
"Mazinho",
"Branco",
"Alemão",
"Edmundo",
"Denílson",
"Elano",
"Alex",
"Luis Fabiano",
"Fred",
"Hulk",
"Gabriel Barbosa",
"Gabriel Jesus",
"Richarlison",
"Vinícius Júnior",
"Rodrygo",
"Raphinha",
"Endrick",
"Casemiro",
"Fabinho",
"Fernandinho",
"Oscar",
"Willian",
"Lucas Moura",
"Douglas Costa",
"Philippe Coutinho",
"Bernard",
"Everton Ribeiro",
"Gerson",
"Bruno Guimarães",
"Lucas Paquetá",
"Andreas Pereira",
"Alisson",
"Ederson",
"Julio Cesar",
"Dida",
"Taffarel",
"Cássio",
"Rogério Ceni",
"Marcos",
"Carlos Alberto Torres",
"Nilton Santos",
"Djalma Santos",
"Bellini",
"Mauro Ramos",
"Moacyr Barbosa",
"Leônidas",
"Ademir",
"Arthur Friedenreich",
"Heleno de Freitas",
"Zizinho",
"Domingos da Guia",
"Falcão",
"Marta",
"Formiga",
"Cristiane",
"Sissi",
"Pretinha",
"Debinha",
"Alexia Putellas",
"Aitana Bonmatí",
"Megan Rapinoe",
"Mia Hamm",
"Abby Wambach",
"Christine Sinclair",
"Birgit Prinz",
"Homare Sawa",
"Wendie Renard",
"Ada Hegerberg",
"Sam Kerr",
"Alex Morgan",
"Carli Lloyd",
"Lotta Schelin",
"Nadine Angerer",
"Hope Solo",
"Lucy Bronze",
"Leah Williamson",
"Lauren Hemp",
"Fran Kirby",
"Eugénie Le Sommer",
"Kadidiatou Diani",
"Marie-Antoinette Katoto",
"Vivianne Miedema",
"Lieke Martens",
"Asisat Oshoala",
"Racheal Kundananji",
"Temwa Chawinga",
"Barbra Banda",
"Linda Caicedo",
"Salma Paralluelo",
"Patri Guijarro",
"Irene Paredes",
"Jennifer Hermoso",
"Jenni Hermoso",
"Mapi León",
"Marta Torrejón",
"Vero Boquete",
"Carolina Morace",
"Hana Mori",
"Sun Wen",
"Wang Shuang",
"Ji So-yun",
"Cho So-hyun",
"Yuki Nagasato",
"Mana Iwabuchi",
"Aya Miyama",
"Futoshi Ikeda",
"Hege Riise",
"Kelly Smith",
"Fara Williams",
"Rachel Daly",
"Millie Bright",
"Mary Earps",
"Hannah Hampton",
"Beth Mead",
"Chloe Kelly",
"Ella Toone",
"Georgia Stanway",
"Keira Walsh",
"Alessia Russo",
"Lauren James",
"Nikita Parris",
"Jill Scott",
"Steph Houghton",
"Karen Carney",
"Eni Aluko",
"Rachel Yankey",
"Alex Scott",
"Casey Stoney",
"Faye White",
"Sue Smith",
"Hope Powell",
"Jackie Groenen",
"Sherida Spitse",
"Daniëlle van de Donk",
"Esmee Brugts",
"Daphne van Domselaar",
"Sari van Veenendaal",
"Manon Melis",
"Mandy van den Berg",
"Desiree van Lunteren",
"Renate Jansen",
"Tessa Wullaert",
"Janice Cayman",
"Nele Gilis",
"John Terry",
"Rio Ferdinand",
"Nemanja Vidić",
"Gary Neville",
"Phil Neville",
"Ashley Cole",
"Sol Campbell",
"Jamie Carragher",
"Ledley King",
"Wes Brown",
"Jaap Stam",
"Michael Carrick",
"Joe Cole",
"David Seaman",
"David James",
"Nigel Martyn",
"Chris Waddle",
"John Barnes",
"Paul Gascoigne",
"Teddy Sheringham",
"Michael Owen",
"Ian Wright",
"Les Ferdinand",
"Andy Cole",
"Robbie Fowler",
"Steve McManaman",
"Emile Heskey",
"Jermain Defoe",
"Peter Crouch",
"Jermaine Jenas",
"Gareth Barry",
"James Milner",
"Jordan Henderson",
"Kyle Walker",
"John Stones",
"Harry Maguire",
"Trent Alexander-Arnold",
"Reece James",
"Ben Chilwell",
"Luke Shaw",
"Declan Rice",
"Jude Bellingham",
"Phil Foden",
"Bukayo Saka",
"Marcus Rashford",
"Jack Grealish",
"Mason Mount",
"Cole Palmer",
"Ollie Watkins",
"Dominic Calvert-Lewin",
"Harry Kane",
"Jadon Sancho",
"Raheem Sterling",
"Callum Wilson",
"Ivan Toney",
"Anthony Gordon",
"Eberechi Eze",
"Conor Gallagher",
"Kobbie Mainoo",
"Adam Lallana",
"Ross Barkley",
"Eric Dier",
"Kalvin Phillips",
"Moussa Sissoko",
"Nabil Fekir",
"Pierre-Emerick Aubameyang",
"Thomas Partey",
"Alexandre Lacazette",
"Ousmane Dembélé",
"Ansu Fati",
"Pedri",
"Gavi",
"Ferran Torres",
"Nico Williams",
"Lamine Yamal",
"Dani Olmo",
"Rodri",
"Mikel Oyarzabal",
"Aymeric Laporte",
"César Azpilicueta",
"Nacho Fernández",
"Raúl Albiol",
"Sergio Reguilón",
"Koke",
"Saúl Ñíguez",
"Thiago Alcântara",
"Marc Bartra",
"José Callejón",
"Jesús Navas",
"Santi Cazorla",
"Xavi Hernández",
"Fernando Morientes",
"Fernando Llorente",
"Aritz Aduriz",
"David Albelda",
"Rubén Baraja",
"Gaizka Mendieta",
"Fernando Hierro",
"Luis Enrique",
"Pep Guardiola",
"Víctor Valdés",
"José Ángel Iribar",
"Andoni Zubizarreta",
"Emilio Butragueño",
"Hugo Sánchez",
"Rafael Márquez",
"Jared Borgetti",
"Cuauhtémoc Blanco",
"Jorge Campos",
"Guillermo Ochoa",
"Javier Hernández",
"Raúl Jiménez",
"Hirving Lozano",
"Carlos Vela",
"Giovani dos Santos",
"Carlos Salcido",
"Claudio Suárez",
"Héctor Herrera",
"Andrés Guardado",
"Jesús Corona",
"Oribe Peralta",
"Luis Roberto Alves",
"Luis Hernández",
"Pável Pardo",
"Ricardo Osorio",
"Miguel Layún",
"Hugo Ayala",
"Néstor Araujo",
"Héctor Moreno",
"Edson Álvarez",
"Santiago Giménez",
"Uriel Antuna",
"Jesús Gallardo",
"Diego Lainez",
"Keylor Navas",
"Paulo Wanchope",
"Bryan Ruiz",
"Celso Borges",
"Joel Campbell",
"Óscar Duarte",
"Giancarlo González",
"Kasey Keller",
"Landon Donovan",
"Claudio Reyna",
"Tim Howard",
"Christian Pulisic",
"Weston McKennie",
"Tyler Adams",
"Gio Reyna",
"Clint Dempsey",
"Michael Bradley",
"Jozy Altidore",
"DaMarcus Beasley",
"Brian McBride",
"Cobi Jones",
"Alexi Lalas",
"Tab Ramos",
"Eric Wynalda",
"Brad Friedel",
"John Harkes",
"DeAndre Yedlin",
"Tim Weah",
"Yunus Musah",
"Folarin Balogun",
"Ricardo Pepi",
"Gianluca Busio",
"Sergiño Dest",
"Antonee Robinson",
"Matt Turner",
"Ivan Rakitić",
"Ivan Perišić",
"Mario Mandžukić",
"Marcelo Brozović",
"Mateo Kovačić",
"Dejan Lovren",
"Vedran Ćorluka",
"Darijo Srna",
"Alen Bokšić",
"Aljoša Asanović",
"Robert Jarni",
"Slaven Bilić",
"Gordon Strachan",
"Kenny Dalglish",
"Graeme Souness",
"Denis Law",
"Jimmy Greaves",
"Kevin Keegan",
"Steve Archibald",
"John Robertson",
"Richard Gough",
"Andy Goram",
"Jim Leighton",
"John McGinn",
"Andrew Robertson",
"Scott McTominay",
"Billy Bremner",
"Lawrie Reilly",
"Dave Mackay",
"Archie Gemmill",
"Mo Johnston",
"Ally McCoist",
"Mark Hateley",
"Paul McStay",
"Gary McAllister",
"Darren Fletcher",
"James McFadden",
"Steven Naismith",
"Kris Boyd",
"Jakub Błaszczykowski",
"Wojciech Szczęsny",
"Piotr Zieliński",
"Arkadiusz Milik",
"Grzegorz Krychowiak",
"Kamil Glik",
"Kamil Grosicki",
"Łukasz Piszczek",
"Jerzy Dudek",
"Maciej Żurawski",
"Euzebiusz Smolarek",
"Jacek Krzynówek",
"Wojciech Kowalewski",
"Artur Boruc",
"Marek Citko",
"Tomasz Hajto",
"Tomasz Frankowski",
"Kazimierz Kmiecik",
"Ernest Pohl",
"Władysław Żmuda",
"Andrzej Szarmach",
"Paweł Janas",
"Marek Koźmiński",
"Marek Leśniak",
"Vladimir Smicer",
"Pavel Nedvěd",
"Petr Čech",
"Tomáš Rosický",
"Karel Poborský",
"Jan Koller",
"Milan Baroš",
"Patrik Berger",
"Tomáš Ujfaluši",
"Pavel Kuka",
"Antonín Panenka",
"Josef Masopust",
"Ivo Viktor",
"Zdeněk Nehoda",
"Karel Brückner",
"Miroslav Kadlec",
"Vladimír Weiss",
"Marek Hamšík",
"Martin Škrtel",
"Robert Vittek",
"Peter Dubovský",
"Róbert Boženík",
"Stanislav Lobotka",
"Juraj Kucka",
"Martin Dúbravka",
"Stefan Kießling",
"Mario Gómez",
"Lars Ricken",
"Torsten Frings",
"Héctor Chumpitaz",
"Teófilo Cubillas",
"Nolberto Solano",
"Juan Vargas",
"Percy Rojas",
"Hugo Sotil",
"César Cueto",
"Elias Figueroa",
"Sergio Livingstone",
"Carlos Caszely",
"Leonel Sánchez",
"Salvador Reyes",
"Elías Figueroa",
"Jorge Burruchaga",
"José Luis Brown",
"Jorge Valdano",
"Omar Sivori",
"Mario Kempes",
"Daniel Passarella",
"Osvaldo Ardiles",
"Ricardo Bochini",
"Américo Gallego",
"René Houseman",
"Leopoldo Luque",
"Ubaldo Fillol",
"Norberto Alonso",
"José Sanfilippo",
"Adolfo Pedernera",
"José Manuel Moreno",
"Omar Corbatta",
"Ángel Labruna",
"Mario Zagallo",
"Didí",
"Mohamed Aboutrika",
"Hossam Hassan",
"Hassan Shehata",
"Ahmed Hassan",
"Wael Gomaa",
"Essam El Hadary",
"Hazem Emam",
"Hany Ramzy",
"Mido",
"Ahmed Hegazi",
"Mohamed Elneny",
"Trézéguet",
"Omar Marmoush",
"Mostafa Mohamed",
"Mahmoud Hassan",
"Emam Ashour",
"Hossam Mido",
"Mohamed Zidan",
"Ahmed Elmohamady",
"Ahmed Fathi",
"Shikabala",
"Amr Zaki",
"Hossam Ashour",
"Ahmed Hassan Mekky",
"Tarek Hamed",
"Abdel-Halim Ali",
"Ali El-Said",
"Ibrahim Hassan",
"Hani Said",
"Wael Reyad",
"Khaled El Gendy",
"Boudewijn Zenden",
"Wim Jonk",
"Frank de Boer",
"Ronald de Boer",
"Edwin van der Sar",
"Phillip Cocu",
"Marc Overmars",
"Pierre van Hooijdonk",
"Rafael van der Vaart",
"Dirk Kuyt",
"Klaas-Jan Huntelaar",
"Memphis Depay",
"Frenkie de Jong",
"Matthijs de Ligt",
"Georginio Wijnaldum",
"Donyell Malen",
"Cody Gakpo",
"Xavi Simons",
"Jeremie Frimpong",
"Denzel Dumfries",
"Marten de Roon",
"Donny van de Beek",
"Ryan Gravenberch",
"Wout Weghorst",
"Steven Berghuis",
"Quincy Promes",
"Luuk de Jong",
"Daley Blind",
"Nathan Aké",
"Stefan de Vrij",
"Tim Krul",
"Maarten Stekelenburg",
"Hans van Breukelen",
"Ruud Hesp",
"Wim Kieft",
"Wout Brama",
"Fernando Couto",
"Deco",
"Pepe",
"Ricardo Carvalho",
"Bruno Alves",
"João Cancelo",
"Nani",
"Bernardo Silva",
"Bruno Fernandes",
"Rúben Neves",
"João Moutinho",
"William Carvalho",
"Raphaël Guerreiro",
"Diogo Jota",
"Gonçalo Ramos",
"Rafael Leão",
"João Félix",
"Vitinha",
"Rúben Dias",
"Nélson Semedo",
"José Fonte",
"Ricardo Quaresma",
"Simão Sabrosa",
"Maniche",
"Costinha",
"Beto",
"Vítor Baía",
"Rui Costa",
"Paulo Sousa",
"Jorge Costa",
"Fernando Meira",
"Nuno Gomes",
"Pauleta",
"Hélder Postiga",
"Luís Boa Morte",
"Mário Coluna",
"José Augusto",
"Fernando Chalana",
"João Pinto",
"Paulo Futre",
"Rui Patrício",
"Ricardo Pereira",
"Nuno Mendes",
"Gonçalo Inácio",
"Otávio",
"Diogo Dalot",
"Fábio Coentrão",
"Éder",
"Ricardo Andrade Quaresma",
"Sergio Conceição",
"Mijat Gacinovic",
"Dragan Džajić",
"Dragan Stojković",
"Branislav Ivanović",
"Aleksandar Kolarov",
"Dušan Tadić",
"Dušan Vlahović",
"Sergej Milinković-Savić",
"Luka Jović",
"Savo Milošević",
"Mateja Kežman",
"Zoran Tošić",
"Milan Jovanović",
"Vladimir Jugović",
"Sinisa Mihajlović",
"Gheorghe Hagi",
"Gheorghe Popescu",
"Adrian Mutu",
"Cristian Chivu",
"Dan Petrescu",
"Florin Răducioiu",
"Ilie Dumitrescu",
"Marius Lăcătuș",
"Dorin Mateuț",
"Gică Popescu",
"Bogdan Stelea",
"Helmut Duckadam",
"László Bölöni",
"Ludovic Giuly",
"Eric Abidal",
"Florent Malouda",
"Sidney Govou",
"Sylvain Wiltord",
"Djibril Cissé",
"Mamadou Niang",
"Fredy Kanouté",
"Seydou Keita",
"Seydou Doumbia",
"Gervinho",
"Salomon Kalou",
"Wilfried Zaha",
"Kolo Touré",
"Emmanuel Eboué",
"Eric Bailly",
"Wilfried Bony",
"Franck Kessié",
"Serge Aurier",
"Maxwel Cornet",
"Jean Michaël Seri",
"Mahmoud El Khatib",
"Essam El-Hadary",
"Ahmed Fathy",
"Rabie Yassin",
"Emad Moteab",
"Marwan Mohsen",
"Ahmed Sayed Zizo",
"Mahmoud Hassan Trezeguet",
"Amr Warda",
"Mohamed Abdelmonem",
"Majed Abdullah",
"Sami Al-Jaber",
"Salem Al-Dawsari",
"Omar Abdulrahman",
"Younes Belhanda"
];

let passwordDeal=[];
let passwordFlipped=[];

function shuffledCopy(arr){
  const a=arr.slice();
  for(let i=a.length-1;i>0;i--){
    const j=Math.floor(Math.random()*(i+1));
    [a[i],a[j]]=[a[j],a[i]];
  }
  return a;
}

function dealPasswordCards(){
  // Keep the full database, but make most rounds noticeably easier.
  // The first 250 names are the familiar/core pool; 2 cards may come from the full database for variety.
  const easyPool=FOOTBALL_PLAYERS.slice(0,250);
  const hardPool=FOOTBALL_PLAYERS.slice(250);
  const easy=shuffledCopy(easyPool).slice(0,8);
  const harder=shuffledCopy(hardPool).slice(0,2);
  passwordDeal=shuffledCopy(easy.concat(harder));
  passwordFlipped=new Array(passwordDeal.length).fill(false);
  renderPasswordGrid();
  toast("اتوزعوا عشرة أسامي جديدة");
}

function togglePasswordCard(i){
  playClickSound();
  passwordFlipped[i]=!passwordFlipped[i];
  if(passwordFlipped[i])playRevealSound();
  renderPasswordGrid();
}

function renderPasswordGrid(){
  const grid=document.getElementById("passwordGrid");
  if(!grid)return;
  grid.textContent="";

  passwordDeal.forEach((name,i)=>{
    const card=document.createElement("div");
    card.className="fb-card"+(passwordFlipped[i]?" flipped":"");
    card.addEventListener("click",()=>togglePasswordCard(i));

    const inner=document.createElement("div");
    inner.className="fb-card-inner";

    const back=document.createElement("div");
    back.className="fb-card-face fb-card-back";
    const ball=document.createElement("span");
    ball.className="fb-ball";
    ball.innerHTML=`<svg viewBox="0 0 100 100" width="34" height="34" aria-hidden="true" class="fb-ball-svg">
      <circle cx="50" cy="50" r="45" fill="#f3f5f8" stroke="#c7ced8" stroke-width="3"/>
      <path d="M50 28l11 8-4 13H43l-4-13z" fill="#111827"/>
      <path d="M39 36L27 32M61 36l12-4M43 49L34 59M57 49l9 10M50 28v-9" fill="none" stroke="#111827" stroke-width="3.5" stroke-linecap="round"/>
      <path d="M34 59l-7 9M66 59l7 9M50 62v13" fill="none" stroke="#111827" stroke-width="3.5" stroke-linecap="round"/>
    </svg>`;
    const idx=document.createElement("span");
    idx.className="fb-index";
    idx.textContent=String(i+1);
    back.append(ball,idx);

    const front=document.createElement("div");
    front.className="fb-card-face fb-card-front";
    const nameSpan=document.createElement("span");
    nameSpan.dir="ltr";
    nameSpan.textContent=name;
    front.appendChild(nameSpan);

    inner.append(back,front);
    card.appendChild(inner);
    grid.appendChild(card);
  });
}


